### ISSUE TITLE
Resolve the installation cliffhanger

### ISSUE THREAD

**Issue by MathieuDuponchelle** [hivejs/docs#2]
I wanted to toy with this project, and <http://docs.hivejs.org/setup/installation.html> guided me faithfully up to the promised state, but it is a pretty frustrating one :)

I have no idea how to create documents, I tried installing my-documents, figured out I needed to run ui-build to get the interface to show up when accessing '/' (or at least I did manage to get to it after that), but no "document-type" is listed in the dropdown menu, and trying to create one anyway raises:

```
Authorization for document:create { body: 
   { data: 
      { type: 'document',
        attributes: [Object],
        relationships: [Object] } } }
[2016-06-13 02:40:18.162] [ERROR] http - Error: Specified document type is not available
    at createWithSnapshot (/home/meh/devel/sandbox/hive/node_modules/hive-core/components/models/src/document.js:67:23)
    at next (native)
    at onFulfilled (/home/meh/devel/sandbox/hive/node_modules/co/index.js:65:19)
    at /home/meh/devel/sandbox/hive/node_modules/co/index.js:54:5
    at Object.co (/home/meh/devel/sandbox/hive/node_modules/co/index.js:50:10)
    at Object.toPromise (/home/meh/devel/sandbox/hive/node_modules/co/index.js:118:63)
    at next (/home/meh/devel/sandbox/hive/node_modules/co/index.js:99:29)
    at onFulfilled (/home/meh/devel/sandbox/hive/node_modules/co/index.js:69:7)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

btw these asynchronous stack traces ain't really useful :(

I also see:

```
[2016-06-13 02:40:12.221] [ERROR] http - Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)
    at vary (/home/meh/devel/sandbox/hive/node_modules/vary/index.js:122:9)
    at Object.module.exports.vary (/home/meh/devel/sandbox/hive/node_modules/koa/lib/response.js:230:5)
    at Object.proto.(anonymous function) [as vary] (/home/meh/devel/sandbox/hive/node_modules/delegates/index.js:40:31)
    at Object.cash (/home/meh/devel/sandbox/hive/node_modules/koa-cash/index.js:26:10)
    at next (native)
    at Object.etag (/home/meh/devel/sandbox/hive/node_modules/koa-etag/index.js:26:12)
    at next (native)
    at Object.conditional (/home/meh/devel/sandbox/hive/node_modules/koa-conditional-get/index.js:16:12)
    at next (native)
    at onFulfilled (/home/meh/devel/sandbox/hive/node_modules/co/index.js:65:19)
    at /home/meh/devel/sandbox/hive/node_modules/co/index.js:54:5
    at Object.co (/home/meh/devel/sandbox/hive/node_modules/co/index.js:50:10)
    at Object.toPromise (/home/meh/devel/sandbox/hive/node_modules/co/index.js:118:63)
    at next (/home/meh/devel/sandbox/hive/node_modules/co/index.js:99:29)
    at onFulfilled (/home/meh/devel/sandbox/hive/node_modules/co/index.js:69:7)
```

But I guess that is unrelated.

I figure a complete quick start guide would at least lead to a point where I can edit a plain text file in two separate sessions :)

**Comment by marcelklehr** [comment]
Hey Matthieu!
You're right, the docs are a bit incomplete atm. What do you say I put in a reference to my-documents and a note explaining the need to run ui-build? Weird that no document types show up for you, did you install any editors?

**Comment by MathieuDuponchelle** [comment]
Hey,

I wouldn't mind that, I'll happily review pull requests if you want preliminary review :)

> What do you say I put in a reference to my-documents and a note explaining the need to run ui-build

> Weird that no document types show up for you, did you install any editors?

I did not explicitly install any editor, but I chose the codemirror option at hive-init time.

**Comment by MathieuDuponchelle** [comment]
Quick update:

After running `npm i hive-editor-text-codemirror; hive ui-build` , the `text/plain` document type became available, and I could succesfully create a document and edit it across multiple sessions, win \o/

I haven't really got free time during my week, but if I do find some time later I'll make a pull request, unless you've already updated the documentation :)

**Comment by MathieuDuponchelle** [comment]
@marcelklehr , I will also explain my use case real quick, in the (not so) secret hope that it might influence your documentation efforts :)

I'm developing a documentation tool that allows for "incremental build" of the documentation, and I'd like to expose a collaborative editing service for it, which would be backed by git.

The basic usage would be:

* visit a page
* click edit
* authenticate yourself somehow
* make changes to the page, with an (ideally collaborative) editor on the left-hand side, and a live preview on the right-hand side.
* Commit your changes with a descriptive message
* The documentation is updated immediately

The live preview will, at least for now, need to be generated by a service wrapping my tool and exposing a simple REST API, because the tool extends the commonmark specification in various ways.

What I think I would need from hivejs here is:

* an API to manage plain text documents programatically, I wouldn't need users to create documents directly for example

* A simple hook to be notified of changes to the plain text document, and update the preview based on that.

I'm considering using hive because it seems promising, and even though it's explicitly not production ready, I don't mind trying bleeding edge stuff for this, as I don't want to advertise this feature as production-ready either

I'd be happy to know your thoughts on that!

**Comment by MathieuDuponchelle** [comment]
Here is a screencast of an earlier version of the feature, which did not work collaboratively but might help seeing what I'm going for : https://youtu.be/jQd1zJIJQRE?t=104

**Comment by marcelklehr** [comment]
re hot doc:
Sounds very cool! Also, hot doc is an ingenious name... :)
The existing [REST API](http://docs.hivejs.org/developing_peripherals/interface_rest_api.html) should be all you need for creating documents and fetching document contents. It implements the [JSON API spec](https://jsonapi.org). In order to be notified of document updates you'd need to create a small hive plugin, though. It turns out the hook you'd need was still missing, so I just took the liberty of [adding it](https://github.com/hivejs/hive-core/commit/c08474a41fde25f7448887fa2a9e1a7aff58a122). The plugin would also need to hook authorization and authentication, of course. You'll be a heavy user of the docs, then. And of course don't hesitate to ask if in doubt!

re hive docs: I updated the relevant pages and the changes should be live at docs.hivejs.org. If you think something's still missing or unclear, let me know!

Btw, I just checked out pitivi. That's an awesome project. The open source world (and I myself, as well) has been in need for a useful video editor for so long!

**Comment by MathieuDuponchelle** [comment]
Aha that's an overwhelmingly positive comment :D 

I'll make sure to update you next time I get to fiddle with hivejs, do you hango out on an IRC channel?

Regarding the doc update, awesome, maybe just specify in the documentation for the my-documents plugin that an editor actually needs to be installed for document types to show up ? And ideally you could make it so it doesn't even let you create a document when no document type is available ?

Closing that task anyway because it served its purpose, thanks!

**Comment by marcelklehr** [comment]
Cool! You can find me in #hive.js on freenode (as analphabet) and in hivejs/chat [on gitter](https://gitter.im/hivejs/chat).
